steps:
  # Passo 1: Construir a imagem de produção
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
      - './mvp/backend'

  # Passo 2: Enviar a imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest']

  # ==============================================================================
  # ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ EDITE ESTA SEÇÃO ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
  # ==============================================================================
  # Passo 3: Executar as migrações do Knex
  - name: 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
    id: 'Migrate'
    entrypoint: 'sh'
    secretEnv: ['DB_USER', 'DB_DATABASE', 'DB_PASSWORD']
    # <<<<< MUDANÇA AQUI: Adicionamos este bloco 'env'
    # Força o DB_HOST a ser 127.0.0.1 para que o Knex se conecte ao Proxy.
    env:
      - 'DB_HOST=127.0.0.1'
    args:
      - '-c'
      - |
        apk add --no-cache wget
        echo "Baixando o Cloud SQL Proxy..."
        wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64 -O /cloud_sql_proxy
        chmod +x /cloud_sql_proxy
        
        echo "Iniciando o Cloud SQL Proxy em background..."
        /cloud_sql_proxy ${_DB_CONNECTION_NAME} &
        
        sleep 5 
        
        echo "Proxy iniciado. Executando migrações do Knex para o ambiente de produção..."
        # <<<<< MUDANÇA AQUI: Adicionamos a flag '--env production'
        # Garante que o Knex use as configurações de 'production' do seu knexfile.js
        npx knex migrate:latest --env production --knexfile ./knexfile.js
  # ==============================================================================
  # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ FIM DA SEÇÃO PARA EDITAR ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
  # ==============================================================================

  # Passo 4: Fazer o deploy da nova imagem no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/gcloud'
    id: 'Deploy'
    args:
      - 'run'
      - 'deploy'
      - 'erpestetica-main'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${_DB_CONNECTION_NAME}'
      - '--set-env-vars=DB_HOST=/cloudsql/${_DB_CONNECTION_NAME}'
      - '--set-secrets=DB_USER=DB_USER:latest,DB_DATABASE=DB_DATABASE:latest,DB_PASSWORD=postgres-password-erp:latest'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest,DB_USER=DB_USER:latest,DB_DATABASE=DB_DATABASE:latest,DB_PASSWORD=postgres-password-erp:latest'

images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'

availableSecrets:
  secretManager:
  - versionName: projects/erp-estetica/secrets/JWT_SECRET/versions/latest
    env: 'JWT_SECRET'
  - versionName: projects/erp-estetica/secrets/DB_USER/versions/latest
    env: 'DB_USER'
  - versionName: projects/erp-estetica/secrets/DB_DATABASE/versions/latest
    env: 'DB_DATABASE'
  - versionName: projects/erp-estetica/secrets/postgres-password-erp/versions/latest
    env: 'DB_PASSWORD'