steps:
  # 1. Constrói a imagem Docker do backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
      - './mvp-estetica/backend'
    id: 'Build'

  # 2. Envia a imagem construída para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
    id: 'Push'

  # 3. Roda as migrações do banco de dados ANTES de fazer o deploy
  # Ele usa a imagem que acabamos de criar, mas executa o comando de migração do knex.
  # As variáveis de ambiente do banco são injetadas como secrets.
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i' # Imagem a ser usada
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
      - '-s' # Conexão com o Cloud SQL
      - '${_DB_CONNECTION_NAME}'
      - '--' # Delimitador para o comando a ser executado no contêiner
      - 'npx'
      - 'knex'
      - 'migrate:latest'
      - '--knexfile'
      - './mvp-estetica/knexfile.js'
    id: 'Migrate'
    secretEnv: ['DB_USER', 'DB_PASSWORD', 'DB_DATABASE', 'DB_HOST']

  # 4. Faz o deploy da nova imagem no Cloud Run
  # Este passo só executa se os passos anteriores (incluindo a migração) forem bem-sucedidos.
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i' # Imagem que será usada no deploy
      - 'gcr.io/cloud-builders/gcloud'
      - 'run'
      - 'deploy'
      - 'syncro-auto-backend' # Nome do seu serviço no Cloud Run
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'
      - '--region'
      - 'us-central1' # Mude para a sua região
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Adicione outras flags conforme necessário (ex: --add-cloudsql-instances)
    id: 'Deploy'
    
# Disponibiliza os segredos do Secret Manager como variáveis de ambiente para o passo de migração
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/DB_DATABASE/versions/latest
      env: 'DB_DATABASE'
    - versionName: projects/$PROJECT_ID/secrets/DB_HOST/versions/latest
      env: 'DB_HOST'

# Define a imagem final que será armazenada
images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/syncro-auto-repo/backend:latest'